//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationNew.UserProfileService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserProfileService.IUserProfileService")]
    public interface IUserProfileService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProfileService/SignIn", ReplyAction="http://tempuri.org/IUserProfileService/SignInResponse")]
        bool SignIn(string userid, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProfileService/SignIn", ReplyAction="http://tempuri.org/IUserProfileService/SignInResponse")]
        System.Threading.Tasks.Task<bool> SignInAsync(string userid, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProfileService/GetUserProfileDetails", ReplyAction="http://tempuri.org/IUserProfileService/GetUserProfileDetailsResponse")]
        UserInfoDataModel.UserInfoDataModel GetUserProfileDetails(string userid, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProfileService/GetUserProfileDetails", ReplyAction="http://tempuri.org/IUserProfileService/GetUserProfileDetailsResponse")]
        System.Threading.Tasks.Task<UserInfoDataModel.UserInfoDataModel> GetUserProfileDetailsAsync(string userid, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProfileService/SignUp", ReplyAction="http://tempuri.org/IUserProfileService/SignUpResponse")]
        bool SignUp(UserProfileDataModel.UserProfileDataModel userProfileDataModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProfileService/SignUp", ReplyAction="http://tempuri.org/IUserProfileService/SignUpResponse")]
        System.Threading.Tasks.Task<bool> SignUpAsync(UserProfileDataModel.UserProfileDataModel userProfileDataModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProfileService/Edit", ReplyAction="http://tempuri.org/IUserProfileService/EditResponse")]
        bool Edit(UserInfoDataModel.UserInfoDataModel userdatamodel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProfileService/Edit", ReplyAction="http://tempuri.org/IUserProfileService/EditResponse")]
        System.Threading.Tasks.Task<bool> EditAsync(UserInfoDataModel.UserInfoDataModel userdatamodel);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserProfileServiceChannel : WebApplicationNew.UserProfileService.IUserProfileService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserProfileServiceClient : System.ServiceModel.ClientBase<WebApplicationNew.UserProfileService.IUserProfileService>, WebApplicationNew.UserProfileService.IUserProfileService {
        
        public UserProfileServiceClient() {
        }
        
        public UserProfileServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserProfileServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserProfileServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserProfileServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool SignIn(string userid, string password) {
            return base.Channel.SignIn(userid, password);
        }
        
        public System.Threading.Tasks.Task<bool> SignInAsync(string userid, string password) {
            return base.Channel.SignInAsync(userid, password);
        }
        
        public UserInfoDataModel.UserInfoDataModel GetUserProfileDetails(string userid, string password) {
            return base.Channel.GetUserProfileDetails(userid, password);
        }
        
        public System.Threading.Tasks.Task<UserInfoDataModel.UserInfoDataModel> GetUserProfileDetailsAsync(string userid, string password) {
            return base.Channel.GetUserProfileDetailsAsync(userid, password);
        }
        
        public bool SignUp(UserProfileDataModel.UserProfileDataModel userProfileDataModel) {
            return base.Channel.SignUp(userProfileDataModel);
        }
        
        public System.Threading.Tasks.Task<bool> SignUpAsync(UserProfileDataModel.UserProfileDataModel userProfileDataModel) {
            return base.Channel.SignUpAsync(userProfileDataModel);
        }
        
        public bool Edit(UserInfoDataModel.UserInfoDataModel userdatamodel) {
            return base.Channel.Edit(userdatamodel);
        }
        
        public System.Threading.Tasks.Task<bool> EditAsync(UserInfoDataModel.UserInfoDataModel userdatamodel) {
            return base.Channel.EditAsync(userdatamodel);
        }
    }
}
