//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationNew.UserProfileService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserProfileService.IUserProfileService")]
    public interface IUserProfileService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProfileService/SignIn", ReplyAction="http://tempuri.org/IUserProfileService/SignInResponse")]
        bool SignIn(string userid, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProfileService/SignIn", ReplyAction="http://tempuri.org/IUserProfileService/SignInResponse")]
        System.Threading.Tasks.Task<bool> SignInAsync(string userid, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProfileService/GetUserProfileDetails", ReplyAction="http://tempuri.org/IUserProfileService/GetUserProfileDetailsResponse")]
        UserInfoDataModel.UserInfoDataModel GetUserProfileDetails(string userid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProfileService/GetUserProfileDetails", ReplyAction="http://tempuri.org/IUserProfileService/GetUserProfileDetailsResponse")]
        System.Threading.Tasks.Task<UserInfoDataModel.UserInfoDataModel> GetUserProfileDetailsAsync(string userid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProfileService/SignUp", ReplyAction="http://tempuri.org/IUserProfileService/SignUpResponse")]
        bool SignUp(string userid, string firstname, string lastname, string email, string birthday, string gender, string addr1, string addr2, string street, string city, string state, string zip, string mobile, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProfileService/SignUp", ReplyAction="http://tempuri.org/IUserProfileService/SignUpResponse")]
        System.Threading.Tasks.Task<bool> SignUpAsync(string userid, string firstname, string lastname, string email, string birthday, string gender, string addr1, string addr2, string street, string city, string state, string zip, string mobile, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProfileService/Edit", ReplyAction="http://tempuri.org/IUserProfileService/EditResponse")]
        bool Edit(string userid, string firstname, string lastname, string email, string addr1, string addr2, string street, string city, string state, string zip, string mobile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProfileService/Edit", ReplyAction="http://tempuri.org/IUserProfileService/EditResponse")]
        System.Threading.Tasks.Task<bool> EditAsync(string userid, string firstname, string lastname, string email, string addr1, string addr2, string street, string city, string state, string zip, string mobile);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserProfileServiceChannel : WebApplicationNew.UserProfileService.IUserProfileService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserProfileServiceClient : System.ServiceModel.ClientBase<WebApplicationNew.UserProfileService.IUserProfileService>, WebApplicationNew.UserProfileService.IUserProfileService {
        
        public UserProfileServiceClient() {
        }
        
        public UserProfileServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserProfileServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserProfileServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserProfileServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool SignIn(string userid, string password) {
            return base.Channel.SignIn(userid, password);
        }
        
        public System.Threading.Tasks.Task<bool> SignInAsync(string userid, string password) {
            return base.Channel.SignInAsync(userid, password);
        }
        
        public UserInfoDataModel.UserInfoDataModel GetUserProfileDetails(string userid) {
            return base.Channel.GetUserProfileDetails(userid);
        }
        
        public System.Threading.Tasks.Task<UserInfoDataModel.UserInfoDataModel> GetUserProfileDetailsAsync(string userid) {
            return base.Channel.GetUserProfileDetailsAsync(userid);
        }
        
        public bool SignUp(string userid, string firstname, string lastname, string email, string birthday, string gender, string addr1, string addr2, string street, string city, string state, string zip, string mobile, string password) {
            return base.Channel.SignUp(userid, firstname, lastname, email, birthday, gender, addr1, addr2, street, city, state, zip, mobile, password);
        }
        
        public System.Threading.Tasks.Task<bool> SignUpAsync(string userid, string firstname, string lastname, string email, string birthday, string gender, string addr1, string addr2, string street, string city, string state, string zip, string mobile, string password) {
            return base.Channel.SignUpAsync(userid, firstname, lastname, email, birthday, gender, addr1, addr2, street, city, state, zip, mobile, password);
        }
        
        public bool Edit(string userid, string firstname, string lastname, string email, string addr1, string addr2, string street, string city, string state, string zip, string mobile) {
            return base.Channel.Edit(userid, firstname, lastname, email, addr1, addr2, street, city, state, zip, mobile);
        }
        
        public System.Threading.Tasks.Task<bool> EditAsync(string userid, string firstname, string lastname, string email, string addr1, string addr2, string street, string city, string state, string zip, string mobile) {
            return base.Channel.EditAsync(userid, firstname, lastname, email, addr1, addr2, street, city, state, zip, mobile);
        }
    }
}
