//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationNew.SignUpWcf {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SignUpWcf.ISignUpWcf")]
    public interface ISignUpWcf {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISignUpWcf/SignUp", ReplyAction="http://tempuri.org/ISignUpWcf/SignUpResponse")]
        bool SignUp(string userid, string firstname, string lastname, string email, string birthday, string gender, string addr1, string addr2, string street, string city, string state, string zip, string mobile, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISignUpWcf/SignUp", ReplyAction="http://tempuri.org/ISignUpWcf/SignUpResponse")]
        System.Threading.Tasks.Task<bool> SignUpAsync(string userid, string firstname, string lastname, string email, string birthday, string gender, string addr1, string addr2, string street, string city, string state, string zip, string mobile, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISignUpWcfChannel : WebApplicationNew.SignUpWcf.ISignUpWcf, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SignUpWcfClient : System.ServiceModel.ClientBase<WebApplicationNew.SignUpWcf.ISignUpWcf>, WebApplicationNew.SignUpWcf.ISignUpWcf {
        
        public SignUpWcfClient() {
        }
        
        public SignUpWcfClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SignUpWcfClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SignUpWcfClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SignUpWcfClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool SignUp(string userid, string firstname, string lastname, string email, string birthday, string gender, string addr1, string addr2, string street, string city, string state, string zip, string mobile, string password) {
            return base.Channel.SignUp(userid, firstname, lastname, email, birthday, gender, addr1, addr2, street, city, state, zip, mobile, password);
        }
        
        public System.Threading.Tasks.Task<bool> SignUpAsync(string userid, string firstname, string lastname, string email, string birthday, string gender, string addr1, string addr2, string street, string city, string state, string zip, string mobile, string password) {
            return base.Channel.SignUpAsync(userid, firstname, lastname, email, birthday, gender, addr1, addr2, street, city, state, zip, mobile, password);
        }
    }
}
