//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationNew.SignInWcf {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SignInWcf.ISignInWcf")]
    public interface ISignInWcf {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISignInWcf/SignIn", ReplyAction="http://tempuri.org/ISignInWcf/SignInResponse")]
        bool SignIn(string userid, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISignInWcf/SignIn", ReplyAction="http://tempuri.org/ISignInWcf/SignInResponse")]
        System.Threading.Tasks.Task<bool> SignInAsync(string userid, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISignInWcfChannel : WebApplicationNew.SignInWcf.ISignInWcf, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SignInWcfClient : System.ServiceModel.ClientBase<WebApplicationNew.SignInWcf.ISignInWcf>, WebApplicationNew.SignInWcf.ISignInWcf {
        
        public SignInWcfClient() {
        }
        
        public SignInWcfClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SignInWcfClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SignInWcfClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SignInWcfClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool SignIn(string userid, string password) {
            return base.Channel.SignIn(userid, password);
        }
        
        public System.Threading.Tasks.Task<bool> SignInAsync(string userid, string password) {
            return base.Channel.SignInAsync(userid, password);
        }
    }
}
